/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.engcia;
// package must be defined in packages from kmodule.xml file

//list any import classes here.
import org.engcia.View.UI
import org.engcia.BC.Hypothesis
import org.engcia.BC.Hypothesis.Finality
import org.engcia.BC.Hypothesis.BudgetType
import org.engcia.BC.Conclusion
import org.engcia.BC.Evidence
import java.io.BufferedReader
import java.io.InputStreamReader
import org.engcia.BD.Storage
import java.util.List
import org.engcia.BD.RAM
import org.engcia.BD.RAMType
import org.engcia.Utils.Questions
import org.engcia.BD.Case



//declare any global variables here

query "Conclusions"
	$conclusion : Conclusion()
end

rule "r1a"
	when
		$hypothesis : Hypothesis( maxBudget >= 300, maxBudget < 600 )
	then
		$hypothesis.budgetType = Hypothesis.BudgetType.BAIXO;
		update($hypothesis);
end

rule "r1b"
	when
		$hypothesis: Hypothesis( maxBudget >= 600, maxBudget < 1000 )
	then
        $hypothesis.budgetType = Hypothesis.BudgetType.MEDIO_BAIXO;
        update($hypothesis);
end

rule "r1c"
	when
		$hypothesis: Hypothesis( maxBudget >= 1000, maxBudget < 1500 )
	then
        $hypothesis.budgetType = Hypothesis.BudgetType.MEDIO;
        update($hypothesis);
end

rule "r1d"
	when
		$hypothesis: Hypothesis( maxBudget >= 1500, maxBudget < 2000 )
	then
        $hypothesis.budgetType = Hypothesis.BudgetType.MEDIO_ALTO;
        update($hypothesis);
end

rule "r1e"
	when
		$hypothesis: Hypothesis( maxBudget >= 2000 )
	then
        $hypothesis.budgetType = Hypothesis.BudgetType.ALTO;
        update($hypothesis);
end

rule "r2a1"
	when
	    $hypothesis : Hypothesis( budgetType == BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_LOW_BUDGET, "1"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_NAVEGACAO_WEB, "1"))
	then
	    $hypothesis.finality = Hypothesis.Finality.NAVEGACAO_WEB_SIMPLES;
		update($hypothesis);
end

rule "r2a2"
	when
	    $hypothesis : Hypothesis( budgetType == BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_LOW_BUDGET, "1"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_NAVEGACAO_WEB, "2"))
	then
	    $hypothesis.finality = Finality.NAVEGACAO_WEB_COMPLEXO;
		update($hypothesis);
end

rule "r2b1"
	when
	    $hypothesis : Hypothesis( budgetType == BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_LOW_BUDGET, "2"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_APLICACOES_OFFICE, "1"))
	then
	    $hypothesis.finality = Finality.APLICACOES_OFFICE_BASICO;
		update($hypothesis);
end

rule "r2b2"
	when
	    $hypothesis : Hypothesis( budgetType == BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_LOW_BUDGET, "2"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_APLICACOES_OFFICE, "2"))
	then
	    $hypothesis.finality = Finality.APLICACOES_OFFICE_PROFISSIONAL;
		update($hypothesis);
end

rule "r2c1"
	when
	    $hypothesis : Hypothesis( budgetType == BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_LOW_BUDGET, "3"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_APLICACOES_PROFISSIONAIS, "1"))
	then
	    $hypothesis.finality = Finality.APLICACOES_PROFISSIONAIS_COM_BASE_DADOS;
		update($hypothesis);
end

rule "r2c2"
	when
	    $hypothesis : Hypothesis( budgetType == BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_LOW_BUDGET, "3"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_APLICACOES_PROFISSIONAIS, "2"))
	then
	    $hypothesis.finality = Finality.APLICACOES_PROFISSIONAIS_SEM_BASE_DADOS;
		update($hypothesis);
end

rule "r3a1"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "1"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_NAVEGACAO_WEB, "1"))
	then
	    $hypothesis.finality = Hypothesis.Finality.NAVEGACAO_WEB_SIMPLES;
		update($hypothesis);
end

rule "r3a2"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "1"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_NAVEGACAO_WEB, "2"))
	then
	    $hypothesis.finality = Finality.NAVEGACAO_WEB_COMPLEXO;
		update($hypothesis);
end

rule "r3b1"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "2"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_APLICACOES_OFFICE, "1"))
	then
	    $hypothesis.finality = Finality.APLICACOES_OFFICE_BASICO;
		update($hypothesis);
end

rule "r3b2"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "2"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_APLICACOES_OFFICE, "2"))
	then
	    $hypothesis.finality = Finality.APLICACOES_OFFICE_PROFISSIONAL;
		update($hypothesis);
end

rule "r3c1"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "3"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_APLICACOES_PROFISSIONAIS, "1"))
	then
	    $hypothesis.finality = Finality.APLICACOES_PROFISSIONAIS_COM_BASE_DADOS;
		update($hypothesis);
end

rule "r3c2"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "3"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_APLICACOES_PROFISSIONAIS, "2"))
	then
	    $hypothesis.finality = Finality.APLICACOES_PROFISSIONAIS_SEM_BASE_DADOS;
		update($hypothesis);
end

rule "r3d1"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "4"))
	then
	    $hypothesis.finality = Finality.JOGOS_BASICOS;
		update($hypothesis);
end

rule "r3e1"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "5"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_PROGRAMAS_AVANÇADOS, "1"))
	then
	    $hypothesis.finality = Finality.PROGRAMAS_AVANÇADOS_MODELACAO_3D;
		update($hypothesis);
end

rule "r3e2"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "5"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_PROGRAMAS_AVANÇADOS, "2"))
	then
	    $hypothesis.finality = Finality.PROGRAMAS_AVANÇADOS_DESIGN_GRAFICO;
		update($hypothesis);
end

rule "r3e3"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "5"))
        eval(UI.answer(Questions.CHOOSE_FINALITY_PROGRAMAS_AVANÇADOS, "3"))
	then
	    $hypothesis.finality = Finality.PROGRAMAS_AVANÇADOS_CALCULO_MATEMATICO;
		update($hypothesis);
end

rule "r3f1"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "6"))
	then
	    $hypothesis.finality = Finality.GAMING;
		update($hypothesis);
end

rule "r3g1"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "7"))
	then
	    $hypothesis.finality = Finality.TRATAMENTO_DE_IMAGEM;
		update($hypothesis);
end

rule "r3h1"
	when
	    $hypothesis : Hypothesis( budgetType != BudgetType.NA, budgetType != BudgetType.BAIXO )
        eval(UI.answer(Questions.CHOOSE_FINALITY_NON_LOW_BUDGET, "8"))
	then
	    $hypothesis.finality = Finality.EDIÇAO_DE_VIDEO_4k_8K;
		update($hypothesis);
end

/*
rule "r4a"
    when
        $hypothesis : Hypothesis( finality == Finality.NAVEGACAO_WEB_SIMPLES )
    then
        $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "240";
        $hypothesis.minRAMPreferred = 8;
        update($hypothesis);
     end

rule "r4b"
    when
        $hypothesis : Hypothesis( finality == Finality.NAVEGACAO_WEB_COMPLEXO )
    then
        $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "240";
        $hypothesis.minRAMPreferred = 16;
        update($hypothesis);
     end
*/

rule "r5a1"
	when
	    $hypothesis : Hypothesis( finality == Finality.NAVEGACAO_WEB_SIMPLES )
        eval(UI.answer(Questions.CHOOSE_FILE_TYPE, "1"))
        eval(UI.answer(Questions.CHOOSE_DURATION_PER_DAY, "1"))
	then
	    $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "240";
        $hypothesis.minRAMPreferred =8;
        update($hypothesis);
end
rule "r5a2"
	when
	    $hypothesis : Hypothesis( finality == Finality.NAVEGACAO_WEB_SIMPLES )
        eval(UI.answer(Questions.CHOOSE_FILE_TYPE, "2"))
        eval(UI.answer(Questions.CHOOSE_DURATION_PER_DAY, "2"))
	then
	    $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "480";
        $hypothesis.minRAMPreferred =8;
        update($hypothesis);
end
rule "r5b1"
	when
	    $hypothesis : Hypothesis( finality == Finality.NAVEGACAO_WEB_COMPLEXO )
        eval(UI.answer(Questions.CHOOSE_FILE_TYPE, "1"))
        eval(UI.answer(Questions.CHOOSE_DURATION_PER_DAY, "1"))
	then
	    $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "240";
        $hypothesis.minRAMPreferred =16;
        update($hypothesis);
end
rule "r5b2"
	when
	    $hypothesis : Hypothesis( finality == Finality.NAVEGACAO_WEB_COMPLEXO )
        eval(UI.answer(Questions.CHOOSE_FILE_TYPE, "2"))
        eval(UI.answer(Questions.CHOOSE_DURATION_PER_DAY, "2"))
	then
	    $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "480";
        $hypothesis.minRAMPreferred =16;
        update($hypothesis);
end
rule "r5c1"
	when
	    $hypothesis : Hypothesis( finality == Finality.APLICACOES_OFFICE_BASICO )
        eval(UI.answer(Questions.CHOOSE_FILE_TYPE, "1"))
        eval(UI.answer(Questions.CHOOSE_DURATION_PER_DAY, "1"))
	then
	    $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "240";
        $hypothesis.minRAMPreferred =8;
        update($hypothesis);
end
rule "r5c2"
	when
	    $hypothesis : Hypothesis( finality == Finality.APLICACOES_OFFICE_BASICO )
        eval(UI.answer(Questions.CHOOSE_FILE_TYPE, "2"))
        eval(UI.answer(Questions.CHOOSE_DURATION_PER_DAY, "2"))
	then
	    $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "480";
        $hypothesis.minRAMPreferred =8;
        update($hypothesis);
end
rule "r5c1"
	when
	    $hypothesis : Hypothesis( finality == Finality.APLICACOES_OFFICE_BASICO )
        eval(UI.answer(Questions.CHOOSE_FILE_TYPE, "1"))
        eval(UI.answer(Questions.CHOOSE_DURATION_PER_DAY, "1"))
	then
	    $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "240";
        $hypothesis.minRAMPreferred =8;
        update($hypothesis);
end
rule "r5c2"
	when
	    $hypothesis : Hypothesis( finality == Finality.APLICACOES_OFFICE_BASICO )
        eval(UI.answer(Questions.CHOOSE_FILE_TYPE, "2"))
        eval(UI.answer(Questions.CHOOSE_DURATION_PER_DAY, "2"))
	then
	    $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "480";
        $hypothesis.minRAMPreferred =8;
        update($hypothesis);
end

rule "r5d1"
	when
	    $hypothesis : Hypothesis( finality == Finality.APLICACOES_OFFICE_PROFISSIONAL )
        eval(UI.answer(Questions.CHOOSE_FILE_TYPE, "1"))
        eval(UI.answer(Questions.CHOOSE_DURATION_PER_DAY, "1"))
	then
	    $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "240";
        $hypothesis.minRAMPreferred =16;
        update($hypothesis);
end
rule "r5d2"
	when
	    $hypothesis : Hypothesis( finality == Finality.APLICACOES_OFFICE_PROFISSIONAL )
        eval(UI.answer(Questions.CHOOSE_FILE_TYPE, "2"))
        eval(UI.answer(Questions.CHOOSE_DURATION_PER_DAY, "2"))
	then
	    $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "480";
        $hypothesis.minRAMPreferred =16;
        update($hypothesis);
end
rule "r5e1"
	when
	    $hypothesis : Hypothesis( finality == Finality.APLICACOES_PROFISSIONAIS_SEM_BASE_DADOS )
        eval(UI.answer(Questions.CHOOSE_DURATION_PER_DAY, "2"))
	then
	    $hypothesis.storage.isSSD = true;
        $hypothesis.storage.capacityGB = "480";
        $hypothesis.minRAMPreferred =16;
        update($hypothesis);
end
//igual ao anterior mas precisamos de mais info do perito
rule "r5e2"
	when
	    $hypothesis : Hypothesis( finality == Finality.APLICACOES_PROFISSIONAIS_COM_BASE_DADOS)
        eval(UI.answer(Questions.CHOOSE_FILE_TYPE, "2"))
        eval(UI.answer(Questions.CHOOSE_DURATION_PER_DAY, "2"))
	then
	   $hypothesis.storage.isSSD = true;
       $hypothesis.storage.capacityGB = "480";
       $hypothesis.minRAMPreferred =16;
       update($hypothesis);
end

rule "r6a1"
	when
	    $hypothesis : Hypothesis( finality != Finality.NA )
        eval(UI.answer(Questions.CHOOSE_OPTIONAL_CASE_COLOR, "1"))
        eval(UI.answer(Questions.CHOOSE_CASE_COLOR, "1"))
	then
	    $hypothesis.caseColorPreferred="black";
        update($hypothesis);
end

rule "r6a2"
	when
	    $hypothesis : Hypothesis( finality != Finality.NA )
        eval(UI.answer(Questions.CHOOSE_OPTIONAL_CASE_COLOR, "1"))
        eval(UI.answer(Questions.CHOOSE_CASE_COLOR, "2"))
	then
	  $hypothesis.caseColorPreferred="white";
      update($hypothesis);

end

rule "r7a1"
	when
	    $hypothesis : Hypothesis( finality != Finality.NA )
        eval(UI.answer(Questions.CHOOSE_CASE_SIZE, "1"))
	then
	  $hypothesis.caseSize=Case.TowerSizeType.MICRO_ATX_TOWER;
      update($hypothesis);

end
rule "r7a2"
	when
	    $hypothesis : Hypothesis( finality != Finality.NA )
        eval(UI.answer(Questions.CHOOSE_CASE_SIZE, "2"))
	then
	  $hypothesis.caseSize=Case.TowerSizeType.MINI_ATX_TOWER;
      update($hypothesis);

end
rule "r7a3"
	when
	    $hypothesis : Hypothesis( finality != Finality.NA )
        eval(UI.answer(Questions.CHOOSE_CASE_SIZE, "3"))
	then
	  $hypothesis.caseSize=Case.TowerSizeType.MID_TOWER;
      update($hypothesis);

end

//rule "r14"
//    when
//        $hypothesis : Hypothesis( finality == Finality.APLICACOES_OFFICE_BASICO )
//    then
//        $hypothesis.storage.isSSD = true;
//        $hypothesis.minRAMPreferred = 8;
//		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
//        System.out.println("Que tipo de ficheiros irão ser mais utilizados? \n");
//        System.out.println("1. Word/excel/PowerPoint \n");
//        System.out.println("2. Imagens ");
//        int choice = Integer.parseInt(br.readLine());
//        if(choice == 1) $hypothesis.storage.capacityGB = "240";
//        else if(choice==2) $hypothesis.storage.capacityGB = "480";
//        update($hypothesis);
//     end
//
//rule "r15"
//    when
//        $hypothesis : Hypothesis( finality == Finality.APLICACOES_OFFICE_PROFISSIONAL )
//    then
//        $hypothesis.storage.isSSD = true;
//        $hypothesis.minRAMPreferred = 16;
//        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
//        System.out.println("Que tipo de ficheiros irão ser mais utilizados? \n");
//        System.out.println("1. Word/excel/PowerPoint \n");
//        System.out.println("2. Imagens ");
//        int choice = Integer.parseInt(br.readLine());
//        if(choice == 1) $hypothesis.storage.capacityGB = "240";
//        else if(choice==2) $hypothesis.storage.capacityGB = "480";
//        update($hypothesis);
//     end
//
//rule "r16"
//    when
//        $hypothesis : Hypothesis( finality == Finality.APLICACOES_PROFISSIONAIS_SEM_BASE_DADOS || finality == Finality.APLICACOES_PROFISSIONAIS_COM_BASE_DADOS )
//    then
//        $hypothesis.storage.isSSD = true;
//        $hypothesis.storage.capacityGB = "240";
//        $hypothesis.minRAMPreferred = 480;
//        update($hypothesis);
//     end
//
//
//rule "r17"
//	when
//		$hypothesis : Hypothesis( finality == Hypothesis.Finality.NAVEGACAO_WEB_SIMPLES || finality == Hypothesis.Finality.NAVEGACAO_WEB_COMPLEXO ||
//		 finality == Hypothesis.Finality.APLICACOES_OFFICE_BASICO || finality == Hypothesis.Finality.APLICACOES_OFFICE_PROFISSIONAL )
//	then
//		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
//        System.out.println("Quando tempo irá utilizar o computador por dia? \n");
//        System.out.println("1. 2 a 4 horas \n");
//        System.out.println("2. Mais de 4 horas \n");
//        int choice = Integer.parseInt(br.readLine());
//        $hypothesis.durationDayChoice = choice;
//        update($hypothesis);
//
//end
//
//rule "r18"
//	when
//		$hypothesis : Hypothesis( finality != Hypothesis.Finality.NA && finality != Hypothesis.Finality.NAVEGACAO_WEB_SIMPLES && finality != Hypothesis.Finality.NAVEGACAO_WEB_COMPLEXO
//		    && finality != Hypothesis.Finality.APLICACOES_OFFICE_BASICO && finality != Hypothesis.Finality.APLICACOES_OFFICE_PROFISSIONAL )
//	then
//		$hypothesis.durationDayChoice = 2;
//        update($hypothesis);
//end
//
//rule "r19"
//	when
//		$hypothesis : Hypothesis ( finality == Hypothesis.Finality.NAVEGACAO_WEB_SIMPLES && finality == Hypothesis.Finality.NAVEGACAO_WEB_COMPLEXO )
//	then
//	    Storage storage = new Storage();
//	    storage.isSSD = true;
//	    storage.capacityGB = "240";
//        List<Storage> storageList = Questions.questionStorage(storage);
//        if(storageList.size() == 2){
//            $hypothesis.scndStorage = storageList.get(1);
//        }
//        $hypothesis.storage = storageList.get(0);
//        update($hypothesis);
//end
//
//rule "r20"
//	when
//		$hypothesis : Hypothesis ( finality == Hypothesis.Finality.APLICACOES_OFFICE_BASICO || finality == Hypothesis.Finality.APLICACOES_OFFICE_PROFISSIONAL )
//	then
//		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
//		Storage storage = new Storage();
//        storage.isSSD = true;
//        System.out.println("Que tipo de ficheiros irão ser mais utilizados? \n");
//        System.out.println("1. Word/excel/PowerPoint \n");
//        System.out.println("2. Imagens ");
//        int choice = Integer.parseInt(br.readLine());
//        if(choice ==1) storage.capacityGB = "240";
//        else if (choice == 2) storage.capacityGB = "480";
//        List<Storage> storageList = Questions.questionStorage(storage);
//        if(storageList.size() == 2){
//            $hypothesis.scndStorage = storageList.get(1);
//        }
//        $hypothesis.storage = storageList.get(0);
//        update($hypothesis);
//end
//
//rule "r21"
//	when
//		$hypothesis : Hypothesis ( finality == Hypothesis.Finality.APLICACOES_PROFISSIONAIS_COM_BASE_DADOS || finality == Hypothesis.Finality.APLICACOES_PROFISSIONAIS_SEM_BASE_DADOS )
//	then
//		Storage storage = new Storage();
//        storage.isSSD = true;
//        storage.capacityGB = "480";
//        List<Storage> storageList = Questions.questionStorage(storage);
//        if(storageList.size() == 2){
//           $hypothesis.scndStorage = storageList.get(1);
//        }
//        $hypothesis.storage = storageList.get(0);
//        update($hypothesis);
//end
//


